package com.lixin.carclassstore.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "AD_INFO".
 */
public class AdInfo {

    private Long configId;
    private Long status;
    private String pageID;
    private String posGroup;
    private String posID;
    private String posWeight;
    private String title;
    private String titleColor;
    private String image;
    private Long width;
    private Long height;
    private Long reqType;
    private String url;
    private Long createTime;
    private Long updateTime;
    private String desc;
    private Long provinceId;
    private Long cityId;
    private Long areaId;
    private Long kindId;
    private Long userId;

    public AdInfo() {
    }

    public AdInfo(Long configId) {
        this.configId = configId;
    }

    public AdInfo(Long configId, Long status, String pageID, String posGroup, String posID, String posWeight, String title, String titleColor, String image, Long width, Long height, Long reqType, String url, Long createTime, Long updateTime, String desc, Long provinceId, Long cityId, Long areaId, Long kindId, Long userId) {
        this.configId = configId;
        this.status = status;
        this.pageID = pageID;
        this.posGroup = posGroup;
        this.posID = posID;
        this.posWeight = posWeight;
        this.title = title;
        this.titleColor = titleColor;
        this.image = image;
        this.width = width;
        this.height = height;
        this.reqType = reqType;
        this.url = url;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.desc = desc;
        this.provinceId = provinceId;
        this.cityId = cityId;
        this.areaId = areaId;
        this.kindId = kindId;
        this.userId = userId;
    }

    public Long getConfigId() {
        return configId;
    }

    public void setConfigId(Long configId) {
        this.configId = configId;
    }

    public Long getStatus() {
        return status;
    }

    public void setStatus(Long status) {
        this.status = status;
    }

    public String getPageID() {
        return pageID;
    }

    public void setPageID(String pageID) {
        this.pageID = pageID;
    }

    public String getPosGroup() {
        return posGroup;
    }

    public void setPosGroup(String posGroup) {
        this.posGroup = posGroup;
    }

    public String getPosID() {
        return posID;
    }

    public void setPosID(String posID) {
        this.posID = posID;
    }

    public String getPosWeight() {
        return posWeight;
    }

    public void setPosWeight(String posWeight) {
        this.posWeight = posWeight;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitleColor() {
        return titleColor;
    }

    public void setTitleColor(String titleColor) {
        this.titleColor = titleColor;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Long getWidth() {
        return width;
    }

    public void setWidth(Long width) {
        this.width = width;
    }

    public Long getHeight() {
        return height;
    }

    public void setHeight(Long height) {
        this.height = height;
    }

    public Long getReqType() {
        return reqType;
    }

    public void setReqType(Long reqType) {
        this.reqType = reqType;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Long getProvinceId() {
        return provinceId;
    }

    public void setProvinceId(Long provinceId) {
        this.provinceId = provinceId;
    }

    public Long getCityId() {
        return cityId;
    }

    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    public Long getAreaId() {
        return areaId;
    }

    public void setAreaId(Long areaId) {
        this.areaId = areaId;
    }

    public Long getKindId() {
        return kindId;
    }

    public void setKindId(Long kindId) {
        this.kindId = kindId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

}
