package com.lixin.carclassstore.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOG_INFO".
 */
public class LogInfo {

    private Long id;
    private Long type;
    private String content;
    private Long createTime;

    public LogInfo() {
    }

    public LogInfo(Long id) {
        this.id = id;
    }

    public LogInfo(Long id, Long type, String content, Long createTime) {
        this.id = id;
        this.type = type;
        this.content = content;
        this.createTime = createTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getType() {
        return type;
    }

    public void setType(Long type) {
        this.type = type;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

}
